require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# temporary build settings to be updated.
install! 'cocoapods', :disable_input_output_paths => true

def capacitorProject
  project 'App', {
    'Debug' => :debug,
    'Release' => :release
  }
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
  pod 'AparajitaCapacitorBiometricAuth', :path => '../../node_modules/@aparajita/capacitor-biometric-auth'
  pod 'BasecomGmbhCapacitorJailbreakRootDetection', :path => '../../node_modules/@basecom-gmbh/capacitor-jailbreak-root-detection'
  pod 'CapawesomeTeamCapacitorDatetimePicker', :path => '../../node_modules/@capawesome-team/capacitor-datetime-picker'
  pod 'CapgoCapacitorSocialLogin', :path => '../../node_modules/@capgo/capacitor-social-login'
  pod 'CapacitorNativeBiometric', :path => '../../node_modules/capacitor-native-biometric'
end

target 'App' do
  capacitorProject
end
